#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# eslint . --ext .js,.ts,.vue --fix #++ 校验所有的.js .ts .vue文件，并修复可自动修复的问题
# git add . #++ 用于将自动修复后改变的文件添加到暂存区
# exit 1 #++ 终止命令，用来测试钩子  会让commit不会真的push 而是只是测试


npm run lint-staged # 因为配置了lint-staged所以不需要配置eslint校验了